# Generated by Django 5.2.4 on 2025-07-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_integration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llmprovider',
            name='created_at',
        ),
        migrations.AddField(
            model_name='llmprovider',
            name='base_url',
            field=models.URLField(default='https://example.com'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
